### ISSUE TITLE
`docker ps` change when both `--quiet` and `--format` options are passed in

### ISSUE THREAD

**Issue by galooph** [codeenigma/ce-dev#120]
Ran into a problem where `ce-dev start` would spin up the first container successfully (a db one), then spit out `WARNING: Ignoring custom format, because both --format and --quiet are set`. The second (web) container wasn't started.

Looking at https://github.com/docker/cli/pull/3666, `docker ps` behaviour has changed, so that when `--quiet` is passed *as well as* `--format`, `quiet` takes precedence and `format` is ignored.

Looks like there are [two occurrences of this in `ce-dev`](https://github.com/search?q=repo%3Acodeenigma%2Fce-dev+--quiet+--format&type=code).

As a quick, local, fix I removed the `--quiet` from `/opt/ce-dev/lib/base-cmd-abstract.js`, which did the trick.

**Comment by gregharvey** [comment]
This should be fixed in v1.2.1.
