### ISSUE TITLE
Make web server config push port 80 to port 443

### ISSUE THREAD

**Issue by gregharvey** [codeenigma/ce-dev#2]
At the moment, certainly for the Mautic web server, there's no rewrite rule from port 80 to port 443. Not a big issue, but causes some head-scratching if someone hits port 80 by accident and gets a connection refused. Would be neater if port 80 pushed people on to 443, to avoid some confusion.

**Comment by pm98zz-c** [comment]
That driven by 2 things, in individual projects configuration:
- exposed ports (or forwarded for Mac)
- nginx config

Looking at the Nginx config for the Mautic install you're referring to, it does normally redirect 80 to 443. So it has to be the exposed port.
Adding it to the expose directive in ce-dev.compose.yml should do, like so:

```
expose:
  - 443
  - 80
```
