### ISSUE TITLE
Create command produced error regarding ifconfig

### ISSUE THREAD

**Issue by philipnorton42** [codeenigma/ce-dev#8]
When I ran the command `ce-dev create` the first bit of output complained about a missing config command.

```
    $ ce-dev create

    Creating private network...
    sudo: ifconfig: command not found
    sudo: ifconfig: command not found
```

My system (Ubuntu 20.04) does not have ifconfig installed. As ifconfig has been deprecated for a number of years it might be best to use the `ip` command instead.

**Comment by pm98zz-c** [comment]
Fair enough, you're happy to take that over?

**Comment by philipnorton42** [comment]
I will give it a go :)
